config/routes.rb
SocialSignup::Engine.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "new" => "users#new", :as => "new"

  resources :sessions
  resources :users
  resources :facebook_users do
    collection do
      get 'signup'
    end
  end
  resources :twitter_users do
    collection do
      get 'signup'
    end
  end

  root :to => "public#index"
end

app/models/social_signup/user.rb
module SocialSignup
  class User < ActiveRecord::Base
    attr_accessible :email, :first_name, :last_name, :password, :password_confirmation
    attr_accessor :password
    before_save :encrypt_password

    #TODO: Need to validate attributes
    validates_confirmation_of :password
    #validates_presence_of :password, :on => :create
    #validates_presence_of :email
    #validates_uniqueness_of :email

    def self.authenticate(email, password)
      user = find_by_email(email)
      if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user
      else
        nil
      end
    end

    def encrypt_password
      if password.present?
        self.password_salt = BCrypt::Engine.generate_salt
        self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
      end
    end
  end
end

app/controllers/social_signup/application_controller.rb
module SocialSignup
  class ApplicationController < ActionController::Base
    helper_method :current_user

    private
    
    def login_user(user)
      session[:user_id] = user.id
    end
    
    def logout_user
      session[:user_id] = nil
    end

    def current_user
      @current_user ||= ::User.find(session[:user_id]) if session[:user_id]
    end
  end
end

app/controllers/social_signup/facebook_users_controller.rb
require_dependency "social_signup/application_controller"

module SocialSignup
  class FacebookUsersController < ApplicationController
    include SocialSignup::Facebook
    
    def signup
      if !authorized?
        return redirect_to_fb_auth
      end
        
      create_user_incl_oauth_token
    end
    
  end
end

app/controllers/social_signup/public_controller.rb
require_dependency "social_signup/application_controller"

module SocialSignup
  class PublicController < ApplicationController
    def index
    end
  end
end

app/controllers/social_signup/sessions_controller.rb
require_dependency "social_signup/application_controller"

module SocialSignup
  class SessionsController < ApplicationController
    def new
    end

    def create
      user = User.authenticate(params[:email], params[:password])
      if user
        login_user(user)
        redirect_to root_url, :notice => "Logged in!"
      else
        flash.now.alert = "Invalid email or password"
        render "new"
      end
    end

    def destroy
      logout_user
      redirect_to root_url, :notice => "Logged out!"
    end
  end
end

app/controllers/social_signup/twitter_users_controller.rb
require_dependency "social_signup/application_controller"

module SocialSignup
  class TwitterUsersController < ApplicationController
    include SocialSignup::Twitter
    
    def signup
      if !authorized?
        return redirect_to_fb_auth
      end

      create_user_incl_oauth_token
    end
    
  end
end

app/controllers/social_signup/users_controller.rb
require_dependency "social_signup/application_controller"

module SocialSignup
  class UsersController < ApplicationController
        
    def index
      @users = ::User.all
    end
    
    def new
      @user = ::User.new
    end
    
    def create
      user = ::User.new(params[:user])
      if user.save
        redirect_to root_path, :notice => "Thank you for signing up!"
      else
        render "new"
      end
    end
    
    def edit
      @user = current_user
    end
    
    def update
      @user = current_user
      if @user.update_attributes(params[:user])
        redirect_to root_path, :notice => "Changes have been added"
      else 
        render :action => 'edit'
      end
    end
    
  end
end

app/helpers/social_signup/application_helper.rb
module SocialSignup
  module ApplicationHelper
  end
end

app/helpers/social_signup/facebook_users_helper.rb
module SocialSignup
  module FacebookUsersHelper
  end
end

app/helpers/social_signup/public_helper.rb
module SocialSignup
  module PublicHelper
  end
end

app/helpers/social_signup/sessions_helper.rb
module SocialSignup
  module SessionsHelper
  end
end

app/helpers/social_signup/twitter_users_helper.rb
module SocialSignup
  module TwitterUsersHelper
  end
end

app/helpers/social_signup/users_helper.rb
module SocialSignup
  module UsersHelper
  end
end

app/views/layouts/social_signup/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialSignup</title>
  <%= stylesheet_link_tag    "social_signup/application", :media => "all" %>
  <%= javascript_include_tag "social_signup/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/social_signup/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>

app/views/social_signup/users/_user.html.erb
<h1>A User</h1>
<p>Username: <%= user.first_name %></p>
<p>Email: <%= user.email %></p>
<p>Password: <%= user.password %></p>

app/views/social_signup/users/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

app/views/social_signup/users/index.html.erb
<h1>All users</h1>

<%= link_to "Add new user", new_user_path %>

<%= render @users %>

app/views/social_signup/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to "Signup with facebook", signup_facebook_users_path %>
<%= link_to "Signup with twitter", signup_twitter_users_path %>